# Generated by Django 3.0.8 on 2021-05-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('ID', models.PositiveIntegerField()),
                ('Kode_Barang', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nama_Barang', models.CharField(max_length=30, null=True)),
                ('Merk', models.CharField(max_length=30, null=True)),
                ('Stock', models.PositiveIntegerField(null=True)),
                ('BAST', models.FileField(upload_to=None, verbose_name='BAST Perolehan')),
            ],
        ),
    ]
