# Generated by Django 3.0.8 on 2021-05-18 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('ID', models.PositiveIntegerField()),
                ('Nama_Gedung', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('MG', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('NIP_NRK', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nama_Pegawai', models.CharField(max_length=30)),
                ('Alamat', models.CharField(max_length=100)),
                ('Telp', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('ID', models.PositiveIntegerField()),
                ('No_Peminjaman', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tgl_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tgl_kembali', models.DateTimeField(null=True)),
                ('BAST', models.FileField(upload_to=None, verbose_name='BAST Disposisi')),
                ('NIP_NRK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('ID', models.PositiveIntegerField()),
                ('Ruang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gedung')),
                ('PJ_Ruang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='PeminjamanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.PositiveIntegerField()),
                ('Gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gedung')),
                ('Kode_Barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Barang')),
                ('No_Peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Peminjaman')),
                ('Ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ruang')),
            ],
        ),
    ]
