# Generated by Django 3.0.8 on 2021-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_gedung_pegawai_peminjaman_peminjamandetail_ruang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='tgl_kembali',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
