# Generated by Django 3.0.8 on 2021-06-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210530_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamandetail',
            name='Kondisi',
            field=models.CharField(choices=[('Bagus', 'Bagus'), ('Rusak', 'Rusak')], max_length=10, null=True),
        ),
    ]
