# Generated by Django 3.0.8 on 2021-06-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_peminjamandetail_kondisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamandetail',
            name='No_Peminjaman',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Peminjaman'),
        ),
    ]
