# Generated by Django 3.0.8 on 2021-06-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210602_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeminjamanDetailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kondisi', models.CharField(max_length=10, null=True)),
                ('Jumlah', models.PositiveIntegerField()),
                ('Gedung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Gedung')),
                ('Kode_Barang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Barang')),
                ('No_Peminjaman', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Peminjaman')),
                ('Ruang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Ruang')),
            ],
        ),
    ]
