# Generated by Django 3.0.8 on 2021-06-05 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_peminjamandetailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamandetailhistory',
            name='tgl_perubahan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
