# Generated by Django 3.0.8 on 2021-06-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210605_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamandetailhistory',
            name='No_Peminjaman',
        ),
        migrations.AddField(
            model_name='peminjamandetailhistory',
            name='No_Peminjaman',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Peminjaman'),
        ),
    ]
