# Generated by Django 3.0.8 on 2021-06-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210605_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjamandetailhistory',
            name='Gedung',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peminjamandetailhistory',
            name='Kode_Barang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peminjamandetailhistory',
            name='Kondisi',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='peminjamandetailhistory',
            name='No_Peminjaman',
        ),
        migrations.AddField(
            model_name='peminjamandetailhistory',
            name='No_Peminjaman',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='peminjamandetailhistory',
            name='Ruang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
